In [10]:
#%%
import cv2
import time
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5', compile = 'False')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1,224,224,3), dtype=np.float32)
import random
possible_input = ['rock','paper','scissor']
computer_input = random.choice(possible_input)

while True:
    ret, frame = cap.read()
    resized_frame = cv2.resize( frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np=np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if (cv2.waitKey(1) & 0xFF == ord('q')):
       break
    elif prediction[0][0] > 0.7:
        user_input = 'rock'
        print('User: ',user_input) 
        print('Computer: ', computer_input) 
        if user_input == computer_input:
            print("Game is Tie")  
        elif user_input == 'rock' and computer_input == 'scissor':
            print("YOU WINS!!COMPUTER LOSE, ROCK SMASHES SCISSOR")
        elif user_input == 'rock' and computer_input == 'paper':
            print("COMPUTER WINS!!YOU LOSE, PAPER COVERS ROCK")   
                               
    elif prediction[0][1] > 0.7:
        user_input = 'paper'
        print('User: ',user_input) 
        print('Computer: ', computer_input)  
        if user_input == computer_input:
           print("Game is Tie")  
        elif user_input == 'paper' and computer_input == 'rock':
           print("YOU WIN!!COMPUTER LOSE,PAPER COVERS ROCK")
        elif user_input == 'paper' and computer_input == 'sciccor':
           print("COMPUTER WINS!!YOU LOSE, SCISSOR CUTS THE PAPER") 
        break                            
    elif prediction[0][2] > 0.7:
        user_input = 'scissor'
        print('User: ',user_input) 
        print('Computer: ', computer_input)
        if user_input == computer_input:
           print("Game is Tie")   
        elif user_input == 'scissor'and computer_input == 'paper':
            print("YOU WINS!!COMPUTER LOSE, SCISSOR CUTS THE PAPER")
        else:
            print("COMPUTER WINS!!YOU LOSE, ROCK SMASHES SCISSOR")   
        break        
    
#time.sleep(2)    
cap.release()
cv2.destroyAllWindows()



[[7.7882456e-03 1.9484786e-04 5.1082283e-05 9.9196589e-01]]
[[8.91404040e-03 2.90539989e-04 1.00812074e-04 9.90694642e-01]]
[[6.8206768e-03 2.2416559e-04 6.2148581e-05 9.9289304e-01]]
[[1.6613925e-02 7.4108661e-04 9.0034380e-05 9.8255491e-01]]
[[1.3381599e-02 7.1973214e-04 1.5465276e-04 9.8574406e-01]]
[[2.1234566e-02 6.4098422e-04 2.0634560e-04 9.7791809e-01]]
[[2.0778719e-02 6.9205678e-04 2.8178320e-04 9.7824746e-01]]
[[2.5292799e-02 3.7428594e-04 2.9882172e-04 9.7403413e-01]]
[[1.9375127e-02 3.9826153e-04 4.3040028e-04 9.7979629e-01]]
[[3.2865841e-02 4.8573536e-04 5.1598332e-04 9.6613240e-01]]
[[2.4007300e-02 2.4576750e-04 2.3553640e-04 9.7551143e-01]]
[[1.3756092e-02 1.6911296e-04 2.5690670e-04 9.8581785e-01]]
[[1.3011336e-02 1.0321752e-04 4.1363997e-04 9.8647183e-01]]
[[5.3383052e-02 5.3940812e-04 1.2717976e-03 9.4480574e-01]]
[[0.5136335  0.00232294 0.07477839 0.4092652 ]]
[[0.74648064 0.00468939 0.09365608 0.15517396]]
User:  rock
Computer:  rock
Game is Tie
[[0.6261202  0.03427