In [1]:
class Vector:
    def __init__(self, vector1):
        self.vector1 = vector1
    def __init__(self, vector2):
        self.vector2 = vector2
        self.coordinates = [vector1, vector2]
    
    def __add__(self, object1,object2):
            return (self.vector1 + object1.vector1 , self.vector2 + object2.vector2)

    def __repr__(self):
        return f'{self.vector1+self.vector2}'

if __name__ == '__main__':

    vector1 = [2,3,5,6]
    vector2 = [1,4,8,6]

    new_vector = vector1+vector2
    print(new_vector)

[2, 3, 5, 6, 1, 4, 8, 6]


In [69]:
class Vector:
    def __init__(self, list = []):
        self.list = list
            
    def __add__(self, other1):
            return (self.list + other1.list)

    def __repr__(self):
        return f'{self.list}'

    vector1 = Vector([2,3,5,6])
    vector2 = Vector([1,4,8,6])

    coordinates = Vector([vector1 , vector2])
    new_vector = Vector(vector1+vector2)
    print(new_vector)

TypeError: __add__() missing 1 required positional argument: 'other2'

In [45]:
import numpy as Vector
class Vector:
    def __init__(self, list = []):
        self.list = list
    
    #def new_list(self, other):
        #new_list = (self.list + other.list for self.list, other.list in zip (self.list , other.list))
        #new_vector =[vector1[0] +vector2[0], vector1[1] +vector2[1]. vector1[2] +vector2[2]]
        #return Vector(new_list)
    def sum_lists(*args):
        return list(map(sum, zip(*args)))

    def __repr__(self):
        return f'{self.list}'

vector1 = [2,3,5]
list.vector2 = Vector([1,4,8])
new_vector = Vector.sum_lists(vector1,vector2)

print(new_vector)


TypeError: can't set attributes of built-in/extension type 'list'

In [13]:
import numpy as Vector
  
in_arr1 = Vector.array([[2, -7, 5], [-6, 2, 0]])
in_arr2 = Vector.array([[5, 8, -5], [3, 6, 9]])
   
print ("1st Input array : ", in_arr1) 
print ("2nd Input array : ", in_arr2) 
    
out_arr = geek.add(in_arr1, in_arr2) 
print ("output added array : ", out_arr)

1st Input array :  [[ 2 -7  5]
 [-6  2  0]]
2nd Input array :  [[ 5  8 -5]
 [ 3  6  9]]
output added array :  [[ 7  1  0]
 [-3  8  9]]


In [14]:
first = [2,3,5,6]
second = [1,4,8,6]

[x + y for x, y in zip(first, second)]

[3, 7, 13, 12]

In [2]:
class Vectorone:
    def __init__(self, vector1):
        self.vector1 = vector1
    def __add__(self, object2):
        return self.vector1 + object2.vector1
class VectorTwo:
    def __init__(self, vector1):
        self.vector1 = vector1
    def __add__(self, object2):
        return self.vector1 + object2.vector1
    def __repr__(self):
        return f"{self.vector1}"
vector1_instance = Vectorone(10)
vector2_instance = VectorTwo(20)
print(vector1_instance + vector2_instance)

30
